#!/bin/bash

# Interactive test script for Fedora line consumption issue
# This script helps diagnose and test the line consumption problem on Fedora Linux

echo "==============================================================================="
echo "FEDORA LINUX - INTERACTIVE LINE CONSUMPTION TEST"
echo "==============================================================================="
echo ""
echo "This test will help diagnose the line consumption issue on your Fedora system."
echo "You'll need to perform the test manually and observe the behavior."
echo ""

LUSUSH_BIN="./builddir/lusush"

if [ ! -f "$LUSUSH_BIN" ]; then
    echo "❌ ERROR: LUSUSH binary not found at $LUSUSH_BIN"
    echo "Please build first with: ninja -C builddir"
    exit 1
fi

echo "🔍 SYSTEM INFORMATION:"
echo "OS: $(uname -a)"
echo "Terminal: $TERM"
echo "Terminal Program: $TERM_PROGRAM"
echo "Shell: $SHELL"
echo "Terminal Size: $(tput lines)x$(tput cols)"
echo ""

echo "==============================================================================="
echo "STEP 1: PREPARE YOUR TERMINAL"
echo "==============================================================================="
echo ""
echo "1. 📏 Resize your terminal window to approximately 20-25 lines tall"
echo "   (This makes it easier to reach the bottom line)"
echo ""
echo "2. 📋 Make note of your current terminal height:"
echo "   Current height: $(tput lines) lines"
echo ""
echo "Press Enter when ready to continue..."
read

echo "==============================================================================="
echo "STEP 2: FILL SCREEN WITH TEST CONTENT"
echo "==============================================================================="
echo ""
echo "We'll fill your screen with numbered lines so you can see if any disappear."
echo ""

# Fill screen with numbered lines
for i in {1..30}; do
    echo "TestLine $i: This line should NEVER disappear during shell editing"
done

echo ""
echo "🎯 IMPORTANT: Look at the lines above this message!"
echo "   - Note the highest line number you can see"
echo "   - Remember this number - we'll check it later"
echo "   - The next prompt should be at or near the bottom of your terminal"
echo ""
echo "Highest visible line number: _____  (fill this in mentally)"
echo ""
echo "Press Enter to start the LUSUSH test..."
read

echo "==============================================================================="
echo "STEP 3: INTERACTIVE LUSUSH TEST"
echo "==============================================================================="
echo ""
echo "🚀 STARTING LUSUSH..."
echo "   When lusush starts, you'll see a prompt at the bottom of your terminal."
echo ""
echo "📝 FOLLOW THESE STEPS EXACTLY:"
echo ""
echo "   1. Type: echo hello world"
echo "   2. Press backspace 5 times (should delete 'world')"
echo "   3. Type: test"
echo "   4. Press Enter"
echo "   5. Expected output: 'hello test'"
echo ""
echo "   6. Type: echo first command"
echo "   7. Press Enter"
echo "   8. Type: echo second command"
echo "   9. Press Enter"
echo "   10. Press UP arrow key (should show 'echo second command')"
echo "   11. Press UP arrow key again (should show 'echo first command')"
echo ""
echo "   12. After each operation, CHECK THE LINES ABOVE!"
echo "       - Are all the TestLine entries still visible?"
echo "       - Is the highest line number the same as before?"
echo "       - If lines disappeared, that's the line consumption bug!"
echo ""
echo "   13. Type 'exit' to quit lusush and return here"
echo ""
echo "🔍 WHAT TO WATCH FOR:"
echo "   ❌ BAD: TestLine entries disappear during editing"
echo "   ❌ BAD: The highest visible line number decreases"
echo "   ❌ BAD: Previous terminal content gets 'consumed'"
echo "   ✅ GOOD: All TestLine entries remain visible"
echo "   ✅ GOOD: Highest line number stays the same"
echo "   ✅ GOOD: Terminal content is preserved"
echo ""
echo "Press Enter to start LUSUSH..."
read

echo "Starting LUSUSH in 3 seconds..."
sleep 1
echo "2..."
sleep 1
echo "1..."
sleep 1
echo ""

# Start LUSUSH
$LUSUSH_BIN

echo ""
echo "==============================================================================="
echo "STEP 4: REPORT RESULTS"
echo "==============================================================================="
echo ""
echo "Now that you've exited lusush, please answer these questions:"
echo ""
echo "1. 🔍 LINE CONSUMPTION CHECK:"
echo "   - Look at the TestLine entries above"
echo "   - Are they all still visible? (Y/N): ____"
echo "   - If some disappeared, which ones? ____"
echo ""
echo "2. 📊 SPECIFIC OPERATIONS:"
echo "   - Did backspace cause line consumption? (Y/N): ____"
echo "   - Did arrow key history cause line consumption? (Y/N): ____"
echo "   - Did typing long commands cause line consumption? (Y/N): ____"
echo ""
echo "3. 🖥️ TERMINAL BEHAVIOR:"
echo "   - Did the cursor bounce around? (Y/N): ____"
echo "   - Did the screen flicker during editing? (Y/N): ____"
echo "   - Were there any visual artifacts? (Y/N): ____"
echo ""
echo "4. 🐛 SEVERITY:"
echo "   - No issues observed: Type 'PASS'"
echo "   - Minor issues: Type 'MINOR'"
echo "   - Major line consumption: Type 'MAJOR'"
echo "   - System unusable: Type 'CRITICAL'"
echo ""
echo "==============================================================================="
echo "DIAGNOSTIC INFORMATION"
echo "==============================================================================="
echo ""
echo "If you experienced line consumption, here's diagnostic info:"
echo ""
echo "🔧 System Info:"
echo "   Fedora Version: $(cat /etc/fedora-release 2>/dev/null || echo 'Unknown')"
echo "   Kernel: $(uname -r)"
echo "   Terminal: $TERM"
echo "   Terminal Size: $(tput lines)x$(tput cols)"
echo "   Shell: $SHELL"
echo ""
echo "🔧 LUSUSH Build Info:"
echo "   Binary: $LUSUSH_BIN"
echo "   Built: $(stat -c %y $LUSUSH_BIN 2>/dev/null || echo 'Unknown')"
echo ""
echo "🔧 Potential Causes on Fedora:"
echo "   - SELinux policies affecting terminal control"
echo "   - Different terminfo database entries"
echo "   - Fedora-specific terminal configurations"
echo "   - GNOME Terminal vs other terminal emulators"
echo "   - Wayland vs X11 display server differences"
echo ""
echo "🔧 Next Steps:"
echo "   If you experienced line consumption, please report:"
echo "   1. Your answers to the questions above"
echo "   2. Which terminal emulator you're using (gnome-terminal, konsole, etc.)"
echo "   3. Whether you're using Wayland or X11"
echo "   4. Any error messages or unusual behavior"
echo ""
echo "==============================================================================="
echo "TEST COMPLETE"
echo "==============================================================================="
