#!/bin/bash

# Test script for history navigation line replacement behavior in LUSUSH
# This test verifies that history navigation replaces the current line
# instead of creating new prompt lines

echo "==============================================================================="
echo "LUSUSH HISTORY NAVIGATION TEST"
echo "==============================================================================="
echo ""

LUSUSH_BIN="./builddir/lusush"

if [ ! -f "$LUSUSH_BIN" ]; then
    echo "❌ ERROR: LUSUSH binary not found at $LUSUSH_BIN"
    echo "Please build first with: ninja -C builddir"
    exit 1
fi

echo "🔍 Testing history navigation line replacement behavior..."
echo ""

echo "==============================================================================="
echo "AUTOMATED TEST: History Command Execution"
echo "==============================================================================="
echo ""

# Test basic history functionality with automated commands
echo "📝 Testing basic history command execution..."

result=$(echo -e "echo first\necho second\necho third\nexit" | timeout 5 $LUSUSH_BIN 2>&1)

if [[ "$result" == *"first"* ]] && [[ "$result" == *"second"* ]] && [[ "$result" == *"third"* ]]; then
    echo "✓ PASSED - Basic history commands executed correctly"
else
    echo "✗ FAILED - Basic history commands failed"
    echo "Output: $result"
fi
echo ""

echo "==============================================================================="
echo "INTERACTIVE TEST INSTRUCTIONS"
echo "==============================================================================="
echo ""
echo "The history navigation issue (creating new prompt lines) can only be"
echo "properly tested interactively. Please follow these steps:"
echo ""

echo "🚀 STEP 1: START LUSUSH"
echo "   Run: $LUSUSH_BIN"
echo ""

echo "📝 STEP 2: CREATE HISTORY ENTRIES"
echo "   Type these commands (press Enter after each):"
echo "   1. echo first command"
echo "   2. echo second command  "
echo "   3. echo third command"
echo ""

echo "🔍 STEP 3: TEST HISTORY NAVIGATION"
echo "   Now test the UP arrow key behavior:"
echo ""
echo "   a) Press UP arrow key once"
echo "      ✅ CORRECT: Should show 'echo third command' on SAME line"
echo "      ❌ WRONG: Creates a new prompt line below"
echo ""
echo "   b) Press UP arrow key again"
echo "      ✅ CORRECT: Should show 'echo second command' on SAME line"
echo "      ❌ WRONG: Creates another new prompt line"
echo ""
echo "   c) Press DOWN arrow key"
echo "      ✅ CORRECT: Should show 'echo third command' on SAME line"
echo "      ❌ WRONG: Creates another new prompt line"
echo ""

echo "🎯 WHAT TO LOOK FOR:"
echo ""
echo "   CORRECT BEHAVIOR:"
echo "   lusush> echo first command"
echo "   first command"
echo "   lusush> echo second command"
echo "   second command  "
echo "   lusush> echo third command"
echo "   third command"
echo "   lusush> echo third command    ← UP arrow replaces this line"
echo ""
echo "   INCORRECT BEHAVIOR (NEW PROMPT LINES):"
echo "   lusush> echo first command"
echo "   first command"
echo "   lusush> echo second command"
echo "   second command"
echo "   lusush> echo third command"
echo "   third command"
echo "   lusush> "
echo "   lusush> echo third command    ← UP arrow creates NEW line"
echo ""

echo "🔧 STEP 4: TEST EDITING ON HISTORY LINES"
echo "   After navigating to a history entry:"
echo "   a) Use LEFT/RIGHT arrows to move cursor"
echo "   b) Use BACKSPACE to delete characters"
echo "   c) Type new characters"
echo "   d) Verify the line is edited IN-PLACE, not on new lines"
echo ""

echo "📊 STEP 5: TEST MIXED OPERATIONS"
echo "   Try combinations of:"
echo "   - UP arrow, edit text, DOWN arrow"
echo "   - UP arrow, backspace, type new text"
echo "   - Navigate through multiple history entries"
echo "   - Each operation should update the SAME line"
echo ""

echo "🚪 STEP 6: EXIT AND REPORT"
echo "   Type 'exit' to quit lusush"
echo "   Then report your observations below"
echo ""

echo "==============================================================================="
echo "DIAGNOSTIC QUESTIONS"
echo "==============================================================================="
echo ""
echo "After running the interactive test, please answer:"
echo ""
echo "1. 🔍 HISTORY NAVIGATION BEHAVIOR:"
echo "   - Does UP arrow replace current line? (Y/N): ____"
echo "   - Does DOWN arrow replace current line? (Y/N): ____"
echo "   - Do new prompt lines get created? (Y/N): ____"
echo ""
echo "2. 📝 LINE EDITING BEHAVIOR:"
echo "   - Can you edit history entries in-place? (Y/N): ____"
echo "   - Does backspace work on history lines? (Y/N): ____"
echo "   - Do cursor movements work correctly? (Y/N): ____"
echo ""
echo "3. 🎯 SPECIFIC ISSUES:"
echo "   - How many extra prompt lines are created? ____"
echo "   - Does it happen with every history navigation? (Y/N): ____"
echo "   - Does it happen only at bottom of terminal? (Y/N): ____"
echo ""
echo "4. 🖥️ TERMINAL INFORMATION:"
echo "   - Terminal emulator: $(ps -p $PPID -o comm= 2>/dev/null || echo 'unknown')"
echo "   - Terminal size: $(tput lines 2>/dev/null || echo '?')x$(tput cols 2>/dev/null || echo '?')"
echo "   - TERM variable: $TERM"
echo "   - Display server: $(echo $XDG_SESSION_TYPE 2>/dev/null || echo 'unknown')"
echo ""

echo "==============================================================================="
echo "COMMON ISSUES AND SOLUTIONS"
echo "==============================================================================="
echo ""
echo "🔧 If you see new prompt lines being created:"
echo ""
echo "   CAUSE: The refresh logic is not properly replacing the current line"
echo "   SYMPTOMS:"
echo "   - Each UP/DOWN arrow creates a new 'lusush>' prompt"
echo "   - History entries appear on new lines instead of replacing current"
echo "   - Terminal fills up with multiple prompt lines"
echo ""
echo "   DEBUGGING:"
echo "   - Note which specific operations trigger it"
echo "   - Check if it happens immediately or after some operations"
echo "   - Observe if cursor position affects the behavior"
echo ""
echo "🔧 If history navigation works but editing doesn't:"
echo ""
echo "   CAUSE: Cursor positioning or refresh logic issues"
echo "   SYMPTOMS:"
echo "   - History shows correctly but can't edit"
echo "   - Backspace doesn't work on history lines"
echo "   - Cursor jumps to wrong positions"
echo ""
echo "🔧 If everything works correctly:"
echo ""
echo "   GREAT! The history navigation is working as expected:"
echo "   - UP/DOWN arrows replace current line content"
echo "   - No extra prompt lines are created"
echo "   - In-place editing works on history entries"
echo ""

echo "==============================================================================="
echo "READY TO TEST"
echo "==============================================================================="
echo ""
echo "Press Enter to start the interactive test, or Ctrl+C to cancel..."
read

echo ""
echo "Starting LUSUSH for interactive history navigation test..."
echo "Follow the steps above and report your findings!"
echo ""
echo "Starting in 3 seconds..."
sleep 1
echo "2..."
sleep 1
echo "1..."
sleep 1
echo ""

# Start LUSUSH for interactive testing
$LUSUSH_BIN

echo ""
echo "==============================================================================="
echo "TEST COMPLETED"
echo "==============================================================================="
echo ""
echo "Thank you for testing! Please review your answers to the diagnostic questions"
echo "above and report any issues with the history navigation behavior."
echo ""
echo "The goal is for history navigation to replace the current line content"
echo "rather than creating new prompt lines."
echo ""
